config/routes.rb
Rozkl::Application.routes.draw do

  resources :sprawdzians
  root :to => 'sprawdzians#index'
end

app/models/sprawdzian.rb
class Sprawdzian < ActiveRecord::Base
	cattr_reader :per_page
	@@per_page=10
    has_attached_file :document
    
    #def self.multiSearch(text)
#		text = "%"+text+"%"
#		#Sprawdzian.where("nazwa like ? OR klasa like ?", text, text)
#		Sprawdzian.find(3)
#    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sprawdzians_controller.rb
class SprawdziansController < ApplicationController
  helper_method :sort_column, :sort_direction

  # GET /sprawdzians
  # GET /sprawdzians.xml
  def index
    query = params[:search_query] ? params[:search_query] : ""
    query = "%"+query+"%" 
    @sprawdzians = Sprawdzian.where('nazwa LIKE ?', query).order(sort_column + " " + sort_direction).paginate :per_page => 1, :page => params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sprawdzians }
    end
  end

  # GET /sprawdzians/1
  # GET /sprawdzians/1.xml
  def show
    @sprawdzian = Sprawdzian.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sprawdzian }
    end
  end

  # GET /sprawdzians/new
  # GET /sprawdzians/new.xml
  def new
    @sprawdzian = Sprawdzian.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sprawdzian }
    end
  end

  # GET /sprawdzians/1/edit
  def edit
    @sprawdzian = Sprawdzian.find(params[:id])
  end

  # POST /sprawdzians
  # POST /sprawdzians.xml
  def create
    @sprawdzian = Sprawdzian.new(params[:sprawdzian])

    respond_to do |format|
      if @sprawdzian.save
        format.html { redirect_to(@sprawdzian, :notice => 'Dodano nowy sprawdzian.')}
        format.xml  { render :xml => @sprawdzian, :status => :created, :location => @sprawdzian }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sprawdzian.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sprawdzians/1
  # PUT /sprawdzians/1.xml
  def update
    @sprawdzian = Sprawdzian.find(params[:id])

    respond_to do |format|
      if @sprawdzian.update_attributes(params[:sprawdzian])
        format.html { redirect_to(@sprawdzian, :notice => 'Sprawdzian was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sprawdzian.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sprawdzians/1
  # DELETE /sprawdzians/1.xml
  def destroy
    @sprawdzian = Sprawdzian.find(params[:id])
    @sprawdzian.destroy

    respond_to do |format|
      format.html { redirect_to(sprawdzians_url) }
      format.xml  { head :ok }
    end
  end
  private
  def sort_column
      Sprawdzian.column_names.include?(params[:sort]) ? params[:sort] : "nazwa"
  end
  def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction]: "asc"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        link_to title, :sort=>column, :direction => direction
    end
end

app/helpers/sprawdzians_helper.rb
module SprawdziansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rozkl</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sprawdzians/_form.html.erb
<%= form_for @sprawdzian, :html => { :multipart => true} do |f| %>
  <% if @sprawdzian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprawdzian.errors.count, "error") %> prohibited this sprawdzian from being saved:</h2>

      <ul>
      <% @sprawdzian.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nazwa %><br />
    <%= f.text_field :nazwa %>
  </div>
  <div class="field">
    <%= f.label :dzial, "Dział" %><br />
    <%= f.text_field :dzial %>
  </div>
  <div class="field">
    <%= f.label :klasa %><br />
    <%= f.text_field :klasa %>
  </div>
  <div class="field">
      <%= f.file_field :document %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sprawdzians/edit.html.erb
<h1>Editing sprawdzian</h1>

<%= render 'form' %>

<%= link_to 'Show', @sprawdzian %> |
<%= link_to 'Back', sprawdzians_path %>

app/views/sprawdzians/index.html.erb
<div id="main">
<h1><%= link_to t(:sprawdzians_list), Sprawdzian %></h1>
<p><i>Kliknij w nazwę kolumny, aby sortować wg niej</i></p>


<form action=''>
<input name="search_query" type="text" />
<input type='submit' value='Szukaj' />
</form>

<hr />
    <table id="sprawdziany">
    <tr>
        <th><%= sortable "nazwa", t(:name) %></th>
        <th><%= sortable "dzial", t(:department) %></th>
        <th><%= sortable "klasa",  t(:class) %></th>
        <th><%= t(:file) %></th>
        <!--<th></th>-->
        <th></th>
        <th></th>
        <th>Data dodania</th>
    </tr>

    <% @sprawdzians.each do |s| %>
    <tr>
        <td><b><%= s.nazwa %></b></td>
        <td><%= s.dzial %></td>
        <td><%= s.klasa %></td>
        <td><%= link_to t(:download), s.document.url %></td>
        <!--<td><%= link_to t(:show), s %></td>-->
        <td><%= link_to t(:edit), edit_sprawdzian_path(s) %></td>
        <td><%= link_to t(:destroy), s, :confirm => t(:are_you_sure), :method => :delete %></td>
        <td><%= s.updated_at.to_s(:db) %></td>
        </tr>
    <% end %>
    </table>
    <div id="pagination">
		<%= will_paginate @sprawdzians %>
	</div>
</div>
<hr />

<%= link_to  t(:new) + ' Sprawdzian', new_sprawdzian_path, :id => "new_button" %>

app/views/sprawdzians/new.html.erb
<h1>New sprawdzian</h1>

<%= render 'form' %>

<%= link_to 'Back', sprawdzians_path %>

app/views/sprawdzians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nazwa:</b>
  <%= @sprawdzian.nazwa %>
</p>

<p>
  <b>Dzial:</b>
  <%= @sprawdzian.dzial %>
</p>

<p>
  <b>Klasa:</b>
  <%= @sprawdzian.klasa %>
</p>


<%= link_to 'Edit', edit_sprawdzian_path(@sprawdzian) %> |
<%= link_to 'Back', sprawdzians_path %>